/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 .\chat.gltf --transform
Author: kentedoloverio24 (https://sketchfab.com/kentedoloverio)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/stackoverflow-keyboard-b4a522dae9ff497793239377a68fd3f2
Title: StackOverflow Keyboard
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function Model(props) {
  const { nodes, materials } = useGLTF("../../../../public/chat-transformed.glb");
  return (
    <group {...props} dispose={null}>
      <group position={[0, -0.12, 0]} scale={[3.5, 0.7, 1.8]}>
        <mesh geometry={nodes.Object_4.geometry} material={materials.Matte_Black} />
        <mesh geometry={nodes.Object_5.geometry} material={materials.Off_White} />
        <mesh geometry={nodes.Object_6.geometry} material={materials.Base_color} />
        <mesh geometry={nodes.Object_7.geometry} material={materials.White} />
        <mesh geometry={nodes.Object_8.geometry} material={materials.Yellow} />
        <mesh geometry={nodes.Object_9.geometry} material={materials.Outline} />
        <mesh geometry={nodes.Object_10.geometry} material={materials.Cable} />
        <mesh geometry={nodes.Object_11.geometry} material={materials.Metal_Case} />
        <mesh geometry={nodes.Object_12.geometry} material={materials.USB_Black} />
      </group>
    </group>
  );
}

useGLTF.preload("../../../../public/chat-transformed.glb");
