/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 .\news.gltf --transform
Author: Woh (https://sketchfab.com/WillBarrow)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/logo-weazel-news-cd9446a911f24373b868634caaa710a5
Title: Logo WEAZEL NEWS
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function Model(props) {
  const { nodes, materials } = useGLTF("/news-transformed.glb");
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={0.01}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group position={[-2.02, -1.24, -25.66]}>
            <mesh geometry={nodes.Null_2_Mat_0.geometry} material={materials.material} />
            <mesh geometry={nodes.Null_2_Mat_0_1.geometry} material={materials.Mat_0} />
            <mesh geometry={nodes.Null_2_Mat1_0.geometry} material={materials["Mat.1"]} />
            <mesh geometry={nodes.Null_2_Mat_0_2.geometry} material={materials.Mat_1} />
          </group>
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/news-transformed.glb");
